-- AgriWatch KE — Supabase Schema
-- © 2026 Cynthia Anguza. All Rights Reserved.
-- IGAD Hackathon 2026 Submission.
--
-- HOW TO RUN:
-- 1. Go to https://bsggvyxjuiqllmxwetsa.supabase.co
-- 2. Click "SQL Editor" in the left sidebar
-- 3. Paste this entire file and click "Run"

-- ─────────────────────────────────────────────
-- 1. GEE prediction cache
--    Stores Earth Engine API results so we don't
--    re-fetch the same county/year data repeatedly.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS gee_cache (
    query_hash  TEXT PRIMARY KEY,
    data        JSONB        NOT NULL,
    created_at  TIMESTAMPTZ  DEFAULT NOW()
);

-- Auto-delete cache entries older than 30 days (keeps free tier storage clean)
CREATE INDEX IF NOT EXISTS idx_gee_cache_created
    ON gee_cache (created_at);


-- ─────────────────────────────────────────────
-- 2. AFA historical statistics
--    Kenya Agriculture & Food Authority data
--    (seeded from afa_official_stats.csv via bootstrap_db.py)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS afa_stats (
    id               SERIAL PRIMARY KEY,
    county           TEXT    NOT NULL,
    crop             TEXT    NOT NULL,
    year             INTEGER NOT NULL,
    area_ha          NUMERIC,
    yield_tha        NUMERIC,
    production_tons  NUMERIC,
    UNIQUE (county, crop, year)
);

CREATE INDEX IF NOT EXISTS idx_afa_county_crop
    ON afa_stats (county, crop);


-- ─────────────────────────────────────────────
-- 3. Yield alert audit trail
--    Every early-warning alert generated by the
--    system is logged here for transparency.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS yield_alerts (
    id               SERIAL PRIMARY KEY,
    county           TEXT    NOT NULL,
    crop             TEXT    NOT NULL,
    year             INTEGER NOT NULL,
    predicted_yield  NUMERIC,
    baseline_yield   NUMERIC,
    deviation_pct    NUMERIC,
    alert_level      TEXT,      -- 'GREEN' | 'ORANGE' | 'RED'
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_county_crop
    ON yield_alerts (county, crop, year);

CREATE INDEX IF NOT EXISTS idx_alerts_level
    ON yield_alerts (alert_level);


-- ─────────────────────────────────────────────
-- Verify: you should see 3 tables created
-- ─────────────────────────────────────────────
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('gee_cache', 'afa_stats', 'yield_alerts');
